import { Product } from './types';
import { calculateProductMetrics, applyABCClassification } from './engine';

// ID da empresa padrão para os dados mockados iniciais
export const DEFAULT_COMPANY_ID = 'default-company-id';

const rawData: Partial<Product>[] = [
  { companyId: DEFAULT_COMPANY_ID, sku: 'SOPH-001', nomeProduto: 'Monitor Gamer 27" 4K', categoria: 'Eletrônicos', marketplace: 'Mercado Livre', marca: 'TechVision', precoVenda: 2499.90, custoProduto: 1600, comissaoMarketplace: 400, custoLogistico: 80, investimentoAds: 150, reclamacaoPercentual: 0.01, origemDados: 'API Mercado Livre', tipoEnvio: 'Full' },
  { companyId: DEFAULT_COMPANY_ID, sku: 'SOPH-002', nomeProduto: 'Teclado Mecânico RGB', categoria: 'Acessórios', marketplace: 'Amazon', marca: 'ClickMaster', precoVenda: 450.00, custoProduto: 120, comissaoMarketplace: 67.50, custoLogistico: 25, investimentoAds: 100, reclamacaoPercentual: 0.00, origemDados: 'API Amazon', tipoEnvio: 'FBA' },
  { companyId: DEFAULT_COMPANY_ID, sku: 'SOPH-003', nomeProduto: 'Cadeira Ergonômica Pro', categoria: 'Móveis', marketplace: 'Shopee', marca: 'ComfortSit', precoVenda: 1290.00, custoProduto: 950, comissaoMarketplace: 258, custoLogistico: 120, investimentoAds: 400, reclamacaoPercentual: 0.05, origemDados: 'XLSX', tipoEnvio: 'Coleta' },
  { companyId: DEFAULT_COMPANY_ID, sku: 'SOPH-004', nomeProduto: 'Mouse Wireless 16k DPI', categoria: 'Acessórios', marketplace: 'Mercado Livre', marca: 'TechVision', precoVenda: 299.00, custoProduto: 180, comissaoMarketplace: 47.84, custoLogistico: 15, investimentoAds: 10, reclamacaoPercentual: 0.02, origemDados: 'API Mercado Livre', tipoEnvio: 'Full' },
  { companyId: DEFAULT_COMPANY_ID, sku: 'SOPH-005', nomeProduto: 'Webcam 1080p Streamer', categoria: 'Eletrônicos', marketplace: 'Amazon', marca: 'LensPro', precoVenda: 350.00, custoProduto: 280, comissaoMarketplace: 52.50, custoLogistico: 20, investimentoAds: 50, reclamacaoPercentual: 0.04, origemDados: 'API Amazon', tipoEnvio: 'FBA' },
  { companyId: DEFAULT_COMPANY_ID, sku: 'SOPH-006', nomeProduto: 'Headset 7.1 Surround', categoria: 'Áudio', marketplace: 'Magalu', marca: 'SoundBlast', precoVenda: 580.00, custoProduto: 300, comissaoMarketplace: 92.80, custoLogistico: 30, investimentoAds: 120, reclamacaoPercentual: 0.01, origemDados: 'CSV', tipoEnvio: 'Correios' },
  { companyId: DEFAULT_COMPANY_ID, sku: 'SOPH-007', nomeProduto: 'SSD NVMe 1TB HighSpeed', categoria: 'Componentes', marketplace: 'Mercado Livre', marca: 'StorageMax', precoVenda: 420.00, custoProduto: 390, comissaoMarketplace: 67.20, custoLogistico: 10, investimentoAds: 0, reclamacaoPercentual: 0.00, origemDados: 'API Mercado Livre', tipoEnvio: 'Full' },
  { companyId: DEFAULT_COMPANY_ID, sku: 'SOPH-008', nomeProduto: 'Smartwatch V2 Sport', categoria: 'Wearables', marketplace: 'Amazon', marca: 'ActiveLife', precoVenda: 890.00, custoProduto: 400, comissaoMarketplace: 133.50, custoLogistico: 18, investimentoAds: 180, reclamacaoPercentual: 0.02, origemDados: 'API Amazon', tipoEnvio: 'FBA' },
  { companyId: DEFAULT_COMPANY_ID, sku: 'SOPH-009', nomeProduto: 'Roteador Wi-Fi 6 Mesh', categoria: 'Redes', marketplace: 'Shopee', marca: 'NetConnect', precoVenda: 750.00, custoProduto: 500, comissaoMarketplace: 150, custoLogistico: 35, investimentoAds: 20, reclamacaoPercentual: 0.01, origemDados: 'API Shopee', tipoEnvio: 'Coleta' },
  { companyId: DEFAULT_COMPANY_ID, sku: 'SOPH-010', nomeProduto: 'Microfone Studio Pro', categoria: 'Áudio', marketplace: 'Amazon', marca: 'SoundBlast', precoVenda: 1100.00, custoProduto: 600, comissaoMarketplace: 165, custoLogistico: 40, investimentoAds: 300, reclamacaoPercentual: 0.03, origemDados: 'Google Sheets', tipoEnvio: 'FBA' },
  { companyId: DEFAULT_COMPANY_ID, sku: 'SOPH-011', nomeProduto: 'Gabinete Mid Tower RGB', categoria: 'Componentes', marketplace: 'Magalu', marca: 'CaseCool', precoVenda: 399.00, custoProduto: 150, comissaoMarketplace: 63.84, custoLogistico: 45, investimentoAds: 40, reclamacaoPercentual: 0.01, origemDados: 'API Magalu', tipoEnvio: 'Magalu Entregas' },
  { companyId: DEFAULT_COMPANY_ID, sku: 'SOPH-012', nomeProduto: 'Placa RTX 3060 12GB', categoria: 'Componentes', marketplace: 'Mercado Livre', marca: 'Grafix', precoVenda: 2199.00, custoProduto: 1900, comissaoMarketplace: 351.84, custoLogistico: 50, investimentoAds: 500, reclamacaoPercentual: 0.08, origemDados: 'API Mercado Livre', tipoEnvio: 'Full' },
  { companyId: DEFAULT_COMPANY_ID, sku: 'SOPH-013', nomeProduto: 'Carregador USB-C 65W', categoria: 'Acessórios', marketplace: 'Loja Própria / Site', marca: 'TechVision', precoVenda: 159.90, custoProduto: 40, comissaoMarketplace: 0, custoLogistico: 12, investimentoAds: 20, reclamacaoPercentual: 0.00, origemDados: 'API Site', tipoEnvio: 'Correios' },
  { companyId: DEFAULT_COMPANY_ID, sku: 'SOPH-014', nomeProduto: 'Caixa de Som BT 20W', categoria: 'Áudio', marketplace: 'B2W / Americanas', marca: 'SoundBlast', precoVenda: 320.00, custoProduto: 150, comissaoMarketplace: 51.20, custoLogistico: 22, investimentoAds: 30, reclamacaoPercentual: 0.01, origemDados: 'API B2W', tipoEnvio: 'B2W Entrega' },
  { companyId: DEFAULT_COMPANY_ID, sku: 'SOPH-015', nomeProduto: 'Mesa Gamer Carbon', categoria: 'Móveis', marketplace: 'Amazon', marca: 'CaseCool', precoVenda: 850.00, custoProduto: 650, comissaoMarketplace: 127.50, custoLogistico: 85, investimentoAds: 100, reclamacaoPercentual: 0.12, origemDados: 'API Amazon', tipoEnvio: 'FBA' }
];

export const MOCK_PRODUCTS: Product[] = applyABCClassification(rawData.map(p => calculateProductMetrics(p as Product)));
